name: Client build
on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [develop]
    paths:
      - '.github/workflows/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/**'
      - 'ios/**'
      - 'android/**'
jobs:
  buildios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.15.17 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
        working-directory: ./
      - run: flutter build ios --no-codesign
  buildandroid:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b v1.15.17 _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - run: flutter pub get
        working-directory: ./
      - run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

      - uses: actions/upload-artifact@v2
        with:
          name: arm64 build
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
          
      - uses: actions/upload-artifact@v2
        with:
          name: arm32 build
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
      
      - uses: actions/upload-artifact@v2
        with:
          name: x86 build
          path: build/app/outputs/apk/release/app-x86_64-release.apk
